### ISSUE TITLE
[Data issue] Wrong ingredients amount for Solar Panel

### ISSUE THREAD

**Issue by davv1** [AnthorNet/DSP-ProductionPlanner#4]
Site says:
![image](https://user-images.githubusercontent.com/13569795/145308873-eb182570-3211-4f1c-b447-4336c2cee28d.png)

This is, from what I see, also used in DSP-Calculator.
However, game says:

![image](https://user-images.githubusercontent.com/13569795/145308906-bd8bf28d-e828-44d9-bc18-c9d43a192778.png)

If you show me how to fix that, I will do PR. But from what I see, data is dragged from your database which we don't have any access as GitHub users (or maybe am I wrong?).
Thanks for attention!

**Comment by davv1** [comment]
Now I saw comment in Calculator...
![image](https://user-images.githubusercontent.com/13569795/145309341-4e634ce8-0bcf-4d69-af6b-df7288bbdf5a.png)

If you want, I can update ALL the data for newest DSP build (9989+) if you tell me how to 😂 

EDIT: Also, if it's harder than few instructions, I can join your Discord. Just tell me if I'm needed over there 😀

**Comment by AnthorNet** [comment]
That one should be fixed, but I need to find an automated way to extract all the data to update them.

**Comment by davv1** [comment]
Thanks a lot!

**Comment by davv1** [comment]
Also, for reading data automagically, I would suggest
<details><summary>this</summary>https://docs.bepinex.dev/master/articles/dev_guide/dev_tools.html</details>

Also, I can help you with this.. Maybe I will learn something new 😄
